name: Lint, test and build
on: [push]
jobs:
    linting-and-prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
            - name: Installing Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: pnpm
                  cache-dependency-path: frontend/pnpm-lock.yaml
            - name: Installing dependencies
              run: cd frontend && pnpm install --frozen-lockfile
            - run: cd frontend && pnpm run tsc
            - run: cd frontend && pnpm run lint
            - run: cd frontend && pnpm run prettier

    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: pnpm
                  cache-dependency-path: frontend/pnpm-lock.yaml
            - name: Installing dependencies
              run: cd frontend && pnpm install --frozen-lockfile
            - run: cd frontend && pnpm run test

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  cache: pnpm
                  cache-dependency-path: frontend/pnpm-lock.yaml
                  node-version: 22.x
            - name: Installing dependencies
              run: cd frontend && pnpm install --frozen-lockfile
            - run: cd frontend && pnpm run build
