name: Lint, test and build
on: [push]
jobs:
    cache-dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: npm
            - uses: actions/cache@v4
              with:
                  path: "**/frontend/node_modules"
                  key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}-${{ hashFiles('**/frontend/package.json') }}
            - name: Installing dependencies
              run: cd frontend && npm ci

    linting-and-prettier:
        runs-on: ubuntu-latest
        needs: cache-dependencies
        steps:
            - uses: actions/checkout@v4
            - name: Installing Node
              uses: actions/setup-node@v4
              with:
                  cache: npm
                  node-version: 22.x
            - uses: actions/cache@v4
              with:
                  path: "**/frontend/node_modules"
                  key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}-${{ hashFiles('**/frontend/package.json') }}
            - name: Installing dependencies
              run: cd frontend && npm ci
            - run: cd frontend && npm run tsc
            - run: cd frontend && npm run lint
            - run: cd frontend && npm run prettier

    unit-tests:
        runs-on: ubuntu-latest
        needs: cache-dependencies
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  cache: npm
                  node-version: 22.x
            - uses: actions/cache@v4
              with:
                  path: "**/frontend/node_modules"
                  key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}-${{ hashFiles('**/frontend/package.json') }}
            - name: Installing dependencies
              run: cd frontend && npm ci
            - run: cd frontend && npm run test

    build:
        runs-on: ubuntu-latest
        needs: cache-dependencies
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  cache: npm
                  node-version: 22.x
            - uses: actions/cache@v4
              with:
                  path: "**/frontend/node_modules"
                  key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}-${{ hashFiles('**/frontend/package.json') }}
            - name: Installing dependencies
              run: cd frontend && npm ci
            - run: cd frontend && npm run build
