name: Lint, test and build
on: [push]
jobs:
    linting-and-prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Installing Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: npm
                  cache-dependency-path: frontend
            - name: Installing dependencies
              run: cd frontend && npm ci
            - run: cd frontend && npm run tsc
            - run: cd frontend && npm run lint
            - run: cd frontend && npm run prettier

    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
                  cache: npm
                  cache-dependency-path: frontend
            - name: Installing dependencies
              run: cd frontend && npm ci
            - run: cd frontend && npm run test

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  cache: npm
                  cache-dependency-path: frontend
                  node-version: 22.x
            - name: Installing dependencies
              run: cd frontend && npm ci
            - run: cd frontend && npm run build
