name: Publish to NPM
on:
    workflow_dispatch:
    push:
        branches:
            - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    id-token: write # Required for OIDC
    contents: write
    pull-requests: write
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  registry-url: "https://registry.npmjs.org"
                  cache: pnpm
                  cache-dependency-path: frontend/pnpm-lock.yaml

            - name: Installing dependencies
              run: cd frontend && pnpm install --frozen-lockfile && pwd
            - name: Create Release Pull Request or Publish
              id: changesets
              uses: changesets/action@e0538e686673de0265c8a3e2904b8c76beaa43fd
              with:
                  publish: pnpm run packages:publish
                  cwd: /home/runner/work/pydantic-forms-ui/pydantic-forms-ui/frontend
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
